# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: irssi-hs
version: '0.0.0'
github: "kleidukos/irssi-hs"
license: MIT
author: "Hécate"
maintainer: "Hécate"
synopsis: A Haskell library to communicate with a running irssi
description: Please see README.md https://github.com/Kleidukos/irssi-hs/blob/master/README.md
category: Network
license-file: LICENSE.md
tested-with: GHC==8.2.2, GHC==8.4.4, GHC==8.6.5, GHC==8.8.3
verbatim:
  cabal-version: 2.2

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

when:
  - condition: "impl(ghc >= 8.4.4)"
    then:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wmissing-export-lists
        - -Wpartial-fields
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind
    else:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind



library:
  exposed-modules:
    - Irssi
    - Irssi.Worker
    - Irssi.Types

  dependencies:
  - aeson                >=1.4.7  && < 1.5
  - bytestring           >=0.10.8 && < 0.11
  - containers           >=0.6.0  && < 0.7
  - text                 >=1.2.3  && <1.3
  - vector               >=0.12.1 && < 0.13
  - directory            >=1.3.3  && < 1.4
  - network              >=3.1.1  && < 3.2
  - base-noprelude       >=4.10   && < 4.14
  - relude               >=0.6.0  && < 0.7
  - unagi-chan           >=0.4.1  && < 0.5
  - unordered-containers >=0.2.10 && < 0.3
  source-dirs: src

tests:
  irssi-hs-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - aeson
    - base-noprelude
    - bytestring
    - irssi-hs
    - relude
    - tasty
    - tasty-hspec
    - text
    - unordered-containers
    - vector
