# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: irssi-hs
version: '0.0.0'
github: "kleidukos/irssi-hs"
license: MIT
author: "Hécate"
maintainer: "Hécate"
synopsis: A Haskell library to communicate with irssi
description: Please see README.md https://github.com/Kleidukos/irssi-hs/blob/master/README.md
category: Network
license-file: LICENSE.md
tested-with: GHC==8.2.2, GHC==8.4.4, GHC==8.6.5, GHC==8.8.3
verbatim:
  cabal-version: 2.4

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

when:
  - condition: "impl(ghc >= 8.4.4)"
    then:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wmissing-export-lists
        - -Wpartial-fields
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind
    else:
      ghc-options:
        - -Wall
        - -Wcompat
        - -Werror
        - -Widentities
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wredundant-constraints
        - -fhide-source-paths
        - -Wno-unused-do-bind

library:
  exposed-modules:
    - Irssi
    - Irssi.Worker
    - Irssi.Types
    - Prelude

  dependencies:
  - aeson          >= 1.4  && < 1.5
  - base-noprelude >= 4.10 && < 4.15
  - bytestring     >= 0.10 && < 0.11
  - containers     >= 0.6  && < 0.7
  - directory      >= 1.3  && < 1.4
  - hspec          >= 2.7  && < 2.8
  - mtl            >= 2.2  && < 2.3
  - network        >= 3.1  && < 3.2
  - relude         >= 0.6  && < 0.8
  - text           >= 1.2  && < 1.3
  - unagi-chan     >= 0.4  && < 0.5
  - unordered-containers >= 0.2 && < 0.3
  - vector         >= 0.12 && < 0.13
  source-dirs: src

tests:
  irssi-hs-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - aeson
    - base-noprelude
    - bytestring
    - irssi-hs
    - relude
    - hspec
    - vector
    - unordered-containers
    - text
    - unordered-containers
    - vector
