# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: irssi-hs
version: '0.0.0'
github: "kleidukos/irssi-hs"
license: MIT
author: "Hécate"
maintainer: "Hécate"
# synopsis: A new Haskeleton package.
# description: irssi-hs is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wpartial-fields

library:
  dependencies:
  - aeson
  - base-noprelude
  - bytestring
  - containers
  - network
  - relude
  - text
  - vector
  source-dirs: src

tests:
  irssi-hs-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - aeson
    - base
    - irssi-hs
    - relude
    - tasty
    - tasty-hspec
