jobs:
  build:
    "runs-on": "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-haskell@v1"
      with:
        "cabal-version": "${{ matrix.cabal }}"
        "ghc-version": "${{ matrix.ghc }}"
    - name: Install dependencies
      run: |
        cabal update
        cabal build --enable-tests --enable-benchmarks --only-dependencies
    - name: Run cabal tests
      run: cabal test
    strategy:
      matrix:
        cabal:
        - '3.0'
        ghc:
        - '8.8.3'
        - '8.6.5'
        - '8.4.4'
        - '8.2.2'
name: Haskell CI
on:
- push
